AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack que incluye roles y políticas de IAM

Resources:
  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/roles.yaml'

  PoliciesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies.yaml'
      # Parameters:
      #   RolClientesIntegrName: !GetAtt RolesStack.Outputs.RolClientesIntegrName
      #   RolClientesIntcusName: !GetAtt RolesStack.Outputs.RolClientesIntcusName
