AWSTemplateFormatVersion: '2010-09-09'
Description: Ejemplo de roles de IAM para dominio de clientes

Resources:
  RolClientesIntegr:
    Type: 'AWS::IAM::Role'
    Properties:
      # RoleName: "sa-eks-integr"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "AllowEksAuthToAssumeRoleForPodIdentity"
            Effect: "Allow"
            Principal:
              Service: "pods.eks.amazonaws.com"
            Action: "sts:AssumeRole"
      # Path: "/clientes/integr/"

  RolClientesIntcus:
    Type: 'AWS::IAM::Role'
    # RoleName: "sa-eks-intcus"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: "AllowEksAuthToAssumeRoleForPodIdentity"
            Effect: "Allow"
            Principal:
              Service: "pods.eks.amazonaws.com"
            Action: "sts:AssumeRole"
      # Path: "/clientes/intcus/"

Outputs:
  RolClientesIntegrName:
    Description: "Name del Rol Clientes Integr"
    Value: !Ref RolClientesIntegr
    Export:
      Name: RolClientesIntegrName

  RolClientesIntcusName:
    Description: "Name del Rol Clientes Intcus"
    Value: !Ref RolClientesIntcus
    Export:
      Name: RolClientesIntcusName