AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack que incluye roles y políticas de IAM

Resources:
  RolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/roles-clientes.yaml'

  PoliciesIntcus:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies-intcus.yaml'

  PoliciesMktven:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies-mktven.yaml'

  PoliciesOnbemi:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies-onbemi.yaml'

  Policies1bluex:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies-1bluex.yaml'

  PoliciesPosaut:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesStack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/clientes/policies-posaut.yaml'