AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack que incluye roles, políticas de IAM para Redes Transversales y Soporte

Resources:
  RolesCorentsu:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/roles-corentsu.yaml'

  PoliciesIntegr:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-integr.yaml'

  PoliciesIntcus:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-intcus.yaml'

  PoliciesMktven:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-mktven.yaml'

  PoliciesOnbemi:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-onbemi.yaml'

  Policies1bluex:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-1bluex.yaml'

  PoliciesPosaut:
    Type: AWS::CloudFormation::Stack
    DependsOn: RolesCorentsu
    Properties:
      TemplateURL: 'https://bx-tecnogia-dev.s3.us-west-2.amazonaws.com/icloud/cfn-nested/corentsu/policies-posaut.yaml'