AWSTemplateFormatVersion: '2010-09-09'
Description: Definición de políticas de IAM

Resources:
  PolicyCorentsuPdoohd:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: "PolicyCorentsuPdoohd"
      Roles:
        - !ImportValue RolCorentsuPdoohdName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "ec2:DescribeInstances*"
            Resource: "*"