name: Deploy Cluster

on:
  push:
    branches:
      - development

env:
  STACK_NAME: "SA-clientes"

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE_CFN }}
        role-session-name: GitHubActionsAWSAccess

    - name: Subir Templates a S3
      run: |
        aws s3 cp cfn/integr/roles-clientes.yaml s3://bx-tecnogia-dev/icloud/cfn-nested/clientes/roles-clientes.yaml
        aws s3 cp cfn/integr/policies-integr.yaml s3://bx-tecnogia-dev/icloud/cfn-nested/clientes/policies-integr.yaml

    - name: Cfn Nested Stack - Role and Policies
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ env.STACK_NAME }}
        template: cfn/integr/nested.yaml
        capabilities: CAPABILITY_NAMED_IAM
        no-fail-on-empty-changeset: '1'